select * from Customer
select * from prod_cat_info
select * from Transactions

select top 1 * from Customer
select top 1 * from prod_cat_info
select top 1 * from Transactions
--------------------------------------DATA PREPARATATION AND UNDERSTANDING-------------------------------------------


--1. What is the total number of rows in each of the 3 tables in the database?
		select COUNT(a.customer_Id) as no_of_rows from Customer  as a
		select COUNT(b.prod_cat) as no_of_rows from prod_cat_info as b
		select COUNT(c.cust_id) as no_of_rows from Transactions as c

--2. What is the total number of transactions that have a return? 
		select COUNT(cust_id) as Count_transactions from Transactions 
		where total_amt like '-%'

--3. As you would have noticed, the dates provided across the datasets are not in a 
--correct format. As first steps, pls convert the date variables into valid date formats 
--before proceeding ahead. 

		select CONVERT (date, DOB, 105) as Dates from Customer

--4. What is the time range of the transaction data available for analysis? Show the 
--output in number of days, months and years simultaneously in different columns. 
		select
		DATENAME(day, tran_date) AS DAY_,
		DATENAME(MONTH, tran_date) AS MONTH_,
		DATENAME(YEAR, tran_date) AS YEAR_
		from Transactions

--5. Which product category does the sub-category “DIY” belong to?
		select prod_cat from prod_cat_info
		where prod_subcat = 'DIY'



---------------------------------------------------DATA ANALYSIS-----------------------------------------------------

--1. Which channel is most frequently used for transactions? 
		select top 1 Store_type from Transactions
		group by store_type
		order by COUNT(Store_type) desc

--2. What is the count of Male and Female customers in the database?
		select TOP 2 Gender,COUNT(Gender) as [Count] from Customer
		group by Gender
		ORDER BY [Count] DESC

--3. From which city do we have the maximum number of customers and how many? 
		select top 1 A.city_code, COUNT(A.city_code) as Cnt_of_Cust from Customer as A
		group by A.city_code
		order by Cnt_of_Cust desc

--4. How many sub-categories are there under the Books category? 
		select COUNT(A.prod_subcat) as [Cnt_of_subcat] from prod_cat_info as A
		where A.prod_cat = 'books'

--5. What is the maximum quantity of products ever ordered? 
		select top 1 Qty from Transactions 
		order by Qty desc

--6. What is the net total revenue generated in categories Electronics and Books?
		select SUM(ABS(B.total_amt)) as Sum_amount from prod_cat_info as A 
		inner join Transactions as B 
		on A.prod_cat_code = B.prod_cat_code
		and A.prod_sub_cat_code = B.prod_subcat_code
		where a.prod_cat in ('books','electronics')


--7. How many customers have >10 transactions with us, excluding returns? 
		select COUNT(T.cust_id) as Cust_count from
		(
		select cust_id, COUNT(cust_id) as Transactions_cnt from Transactions
		group by cust_id
		having COUNT(cust_id)>10
		) as T

--8. What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories, from “Flagship stores”? 
		select SUM(ABS(B.total_amt)) as Sum_amount from prod_cat_info as A 
		inner join Transactions as B 
		on A.prod_cat_code = B.prod_cat_code
		and A.prod_sub_cat_code = B.prod_subcat_code
		where B.Store_type = 'flagship store' and A.prod_cat in ('clothing','electronics')

--9. What is the total revenue generated from “Male” customers in “Electronics” 
--category? Output should display total revenue by prod sub-cat. 
		select C.prod_subcat ,SUM(ABS(B.total_amt)) as Sum_amount from Customer as A
		inner join Transactions as B
		on A.customer_Id = B.cust_id
		inner join prod_cat_info as C
		on B.prod_cat_code = C.prod_cat_code
		and B.prod_subcat_code = C.prod_sub_cat_code
		where Gender = 'M' and C.prod_cat = 'electronics'
		group by C.prod_subcat

--10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales? 
		SELECT TOP 5 prod_subcat, SUM(ABS(total_amt))/(SELECT SUM(ABS(total_amt)) FROM Transactions)*100 AS SALES_PERCENT  
		from prod_cat_info AS A 
		INNER JOIN Transactions as B 
		on A.prod_cat_code = B.prod_cat_code
		AND A.prod_sub_cat_code = B.prod_subcat_code
		GROUP BY prod_subcat
		ORDER BY SUM(ABS(total_amt))/(SELECT SUM(ABS(total_amt)) FROM Transactions)*100 DESC

--11. For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data? 

		select customer_Id, SUM(ABS(total_amt)) Net_Ttl_Revenue, DATEDIFF(YEAR,DOB,GETDATE()) as Age from Customer as a
		inner join Transactions as b 
		on a.customer_Id = b.cust_id
		where DATEDIFF(YEAR,DOB,GETDATE()) between 25 and 35
		and tran_date>=(select DATEADD(DAY,-30,MAX(tran_date)) from Transactions)
		group by customer_Id,  DATEDIFF(YEAR,DOB,GETDATE())
		
		
--12.Which product category has seen the max value of returns in the last 3 months of transactions? 
		select top 1 prod_cat, ROUND(SUM(ABS(total_amt)), 2) as Returns_ from prod_cat_info as a
		inner join Transactions as b
		on a.prod_cat_code = b.prod_cat_code and 
		a.prod_sub_cat_code = b.prod_subcat_code		
		where tran_date between (select  DATEADD(MONTH,-3, MAX(tran_date)) from Transactions)
		and (select MAX(tran_date) from Transactions) 
		group by prod_cat
		order by Returns_ desc
		
--13.Which store-type sells the maximum products; by value of sales amount and by 
--quantity sold? 
		select top 1 a.Store_type, ROUND(ABS(SUM(a.total_amt)),2) as Total_Amt, SUM(a.Qty) as Quantity 
		from Transactions as a
		group by Store_type 
		order by Total_Amt desc, Quantity desc

--14.What are the categories for which average revenue is above the overall average. 
		select prod_cat, round(AVG(ABS(total_amt)), 4) as Avg_revenue from prod_cat_info as a
		inner join Transactions as b
		on a.prod_cat_code = b.prod_cat_code and
		a.prod_sub_cat_code = b.prod_subcat_code
		group by prod_cat
		having AVG(ABS(total_amt))>(select avg(ABS(total_amt)) from Transactions)

--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.
		select a.prod_cat, a.prod_subcat, AVG(ABS(b.total_amt)) as Avg_Amt, SUM(ABS(b.total_amt)) as Total_amt 
		from prod_cat_info as a
		inner join Transactions as b
		on a.prod_cat_code = b.prod_cat_code and
		a.prod_sub_cat_code = b.prod_subcat_code
		where a.prod_cat in (
							select top 5 prod_cat from prod_cat_info as a
							inner join Transactions as b
							on a.prod_cat_code = b.prod_cat_code and
							a.prod_sub_cat_code = b.prod_subcat_code
							group by prod_cat
							order by SUM(ABS(Qty)) desc
							)
		group by a.prod_cat, a.prod_subcat
		order by a.prod_cat, a.prod_subcat
					
		